### ISSUE TITLE
How can i clear/remove old value when change to new multiselect formfield

### ISSUE THREAD

**Issue by Thaimay** [cetorres/multiselect_formfield#32]
Here my follow. Thanks
--------------------------
1. ![image](https://user-images.githubusercontent.com/11836057/99758146-88913700-2b23-11eb-9b2b-c66880eed73e.png)
2. ![image](https://user-images.githubusercontent.com/11836057/99758161-9050db80-2b23-11eb-85b2-0f4ee5fbd6cd.png)
3. ![image](https://user-images.githubusercontent.com/11836057/99758176-9646bc80-2b23-11eb-92ef-8940af0ae811.png)
4. ![image](https://user-images.githubusercontent.com/11836057/99758190-9b0b7080-2b23-11eb-9371-ef2372121175.png) <--- because new multiselect formfield dont have selected item.
5. ![image](https://user-images.githubusercontent.com/11836057/99758199-9fd02480-2b23-11eb-96e8-660873d52342.png)

**Comment by ayinloya** [comment]
I'm also getting this issue, Any solution yet?

**Comment by rsree1210** [comment]
I am also facing the same issue.
Any update on when the plugin will fix this issue?
Or any alternative solution can be used to clear the field?

**Comment by hampsterx** [comment]
very temp fix, use my fork :(

https://github.com/cetorres/multiselect_formfield/compare/master...hampsterx:issue_32_clear_old_value_bug

this add a key and also avoids null bug here.

```
multiselect_formfield:
    # https://github.com/cetorres/multiselect_formfield/issues/32
    git:
      url: git://github.com/hampsterx/multiselect_formfield.git
      ref: issue_32_clear_old_value_bug
```

Didn't submit PR as wasn't sure if this is right fix or not. Works ok tho..
